Error with clearing tables: name 'Account' is not defined at Sat Nov 27 05:28:58 2021
Error with creating triggers: (pymysql.err.OperationalError) (1359, 'Trigger already exists')
[SQL: CREATE TRIGGER autoupdatePrice_2 AFTER UPDATE ON Service
                                FOR EACH ROW BEGIN
                                    INSERT INTO PriceHistory(ServiceName, CompanyName, Price) VALUES (NEW.ServiceName, NEW.CompanyName, NEW.ServicePrice);
                                END]
(Background on this error at: https://sqlalche.me/e/14/e3q8) at Sat Nov 27 05:49:23 2021
Error with initializing tables: (pymysql.err.IntegrityError) (1062, "Duplicate entry '1000' for key 'Account.PRIMARY'")
[SQL: INSERT INTO `Account` (`ID`, `AccountLogin`, `AccountPassword`, `MobileNumber`, `Email`, `Rolename`) VALUES (%(ID)s, %(AccountLogin)s, %(AccountPassword)s, %(MobileNumber)s, %(Email)s, %(Rolename)s)]
[parameters: {'ID': 1000, 'AccountLogin': 'ur_god', 'AccountPassword': 'god_pass', 'MobileNumber': '+375(99)999-99-99', 'Email': 'godemail@god.ru', 'Rolename': 'BROKER'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) at Sat Nov 27 05:49:23 2021
Error with creating triggers: (pymysql.err.OperationalError) (1359, 'Trigger already exists')
[SQL: CREATE TRIGGER autoupdatePrice_2 AFTER UPDATE ON Service
                                FOR EACH ROW BEGIN
                                    INSERT INTO PriceHistory(ServiceName, CompanyName, Price) VALUES (NEW.ServiceName, NEW.CompanyName, NEW.ServicePrice);
                                END]
(Background on this error at: https://sqlalche.me/e/14/e3q8) at Sat Nov 27 05:50:55 2021
Error with initializing tables: (pymysql.err.IntegrityError) (1062, "Duplicate entry '1000' for key 'Account.PRIMARY'")
[SQL: INSERT INTO `Account` (`ID`, `AccountLogin`, `AccountPassword`, `MobileNumber`, `Email`, `Rolename`) VALUES (%(ID)s, %(AccountLogin)s, %(AccountPassword)s, %(MobileNumber)s, %(Email)s, %(Rolename)s)]
[parameters: {'ID': 1000, 'AccountLogin': 'ur_god', 'AccountPassword': 'god_pass', 'MobileNumber': '+375(99)999-99-99', 'Email': 'godemail@god.ru', 'Rolename': 'BROKER'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) at Sat Nov 27 05:50:55 2021
Error with creating triggers: (pymysql.err.OperationalError) (1359, 'Trigger already exists')
[SQL: CREATE TRIGGER autoupdatePrice_2 AFTER UPDATE ON Service
                                FOR EACH ROW BEGIN
                                    INSERT INTO PriceHistory(ServiceName, CompanyName, Price) VALUES (NEW.ServiceName, NEW.CompanyName, NEW.ServicePrice);
                                END]
(Background on this error at: https://sqlalche.me/e/14/e3q8) at Sat Nov 27 05:53:00 2021
Error with initializing tables: (pymysql.err.IntegrityError) (1062, "Duplicate entry '1000' for key 'Account.PRIMARY'")
[SQL: INSERT INTO `Account` (`ID`, `AccountLogin`, `AccountPassword`, `MobileNumber`, `Email`, `Rolename`) VALUES (%(ID)s, %(AccountLogin)s, %(AccountPassword)s, %(MobileNumber)s, %(Email)s, %(Rolename)s)]
[parameters: {'ID': 1000, 'AccountLogin': 'ur_god', 'AccountPassword': 'god_pass', 'MobileNumber': '+375(99)999-99-99', 'Email': 'godemail@god.ru', 'Rolename': 'BROKER'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) at Sat Nov 27 05:53:00 2021
Error with creating triggers: (pymysql.err.OperationalError) (1359, 'Trigger already exists')
[SQL: CREATE TRIGGER autoupdatePrice_2 AFTER UPDATE ON Service
                                FOR EACH ROW BEGIN
                                    INSERT INTO PriceHistory(ServiceName, CompanyName, Price) VALUES (NEW.ServiceName, NEW.CompanyName, NEW.ServicePrice);
                                END]
(Background on this error at: https://sqlalche.me/e/14/e3q8) at Sat Nov 27 05:53:29 2021
Error with initializing tables: (pymysql.err.IntegrityError) (1062, "Duplicate entry '1000' for key 'Account.PRIMARY'")
[SQL: INSERT INTO `Account` (`ID`, `AccountLogin`, `AccountPassword`, `MobileNumber`, `Email`, `Rolename`) VALUES (%(ID)s, %(AccountLogin)s, %(AccountPassword)s, %(MobileNumber)s, %(Email)s, %(Rolename)s)]
[parameters: {'ID': 1000, 'AccountLogin': 'ur_god', 'AccountPassword': 'god_pass', 'MobileNumber': '+375(99)999-99-99', 'Email': 'godemail@god.ru', 'Rolename': 'BROKER'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) at Sat Nov 27 05:53:29 2021
Error with creating triggers: (pymysql.err.OperationalError) (1359, 'Trigger already exists')
[SQL: CREATE TRIGGER autoupdatePrice_2 AFTER UPDATE ON Service
                                FOR EACH ROW BEGIN
                                    INSERT INTO PriceHistory(ServiceName, CompanyName, Price) VALUES (NEW.ServiceName, NEW.CompanyName, NEW.ServicePrice);
                                END]
(Background on this error at: https://sqlalche.me/e/14/e3q8) at Sat Nov 27 05:54:14 2021
Error with initializing tables: (pymysql.err.IntegrityError) (1062, "Duplicate entry '1000' for key 'Account.PRIMARY'")
[SQL: INSERT INTO `Account` (`ID`, `AccountLogin`, `AccountPassword`, `MobileNumber`, `Email`, `Rolename`) VALUES (%(ID)s, %(AccountLogin)s, %(AccountPassword)s, %(MobileNumber)s, %(Email)s, %(Rolename)s)]
[parameters: {'ID': 1000, 'AccountLogin': 'ur_god', 'AccountPassword': 'god_pass', 'MobileNumber': '+375(99)999-99-99', 'Email': 'godemail@god.ru', 'Rolename': 'BROKER'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) at Sat Nov 27 05:54:14 2021
Error with creating triggers: (pymysql.err.OperationalError) (1359, 'Trigger already exists')
[SQL: CREATE TRIGGER autoupdatePrice_2 AFTER UPDATE ON Service
                                FOR EACH ROW BEGIN
                                    INSERT INTO PriceHistory(ServiceName, CompanyName, Price) VALUES (NEW.ServiceName, NEW.CompanyName, NEW.ServicePrice);
                                END]
(Background on this error at: https://sqlalche.me/e/14/e3q8) at Sat Nov 27 05:55:34 2021
Error with initializing tables: (pymysql.err.IntegrityError) (1062, "Duplicate entry '1000' for key 'Account.PRIMARY'")
[SQL: INSERT INTO `Account` (`ID`, `AccountLogin`, `AccountPassword`, `MobileNumber`, `Email`, `Rolename`) VALUES (%(ID)s, %(AccountLogin)s, %(AccountPassword)s, %(MobileNumber)s, %(Email)s, %(Rolename)s)]
[parameters: {'ID': 1000, 'AccountLogin': 'ur_god', 'AccountPassword': 'god_pass', 'MobileNumber': '+375(99)999-99-99', 'Email': 'godemail@god.ru', 'Rolename': 'BROKER'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) at Sat Nov 27 05:55:34 2021
Error with creating triggers: (pymysql.err.OperationalError) (1359, 'Trigger already exists')
[SQL: CREATE TRIGGER autoupdatePrice_2 AFTER UPDATE ON Service
                                FOR EACH ROW BEGIN
                                    INSERT INTO PriceHistory(ServiceName, CompanyName, Price) VALUES (NEW.ServiceName, NEW.CompanyName, NEW.ServicePrice);
                                END]
(Background on this error at: https://sqlalche.me/e/14/e3q8) at Sat Nov 27 15:24:24 2021
Error with initializing tables: 'DbInitializer' object has no attribute 'create_session' at Sat Nov 27 15:24:28 2021
Error with initializing tables: 'DbInitializer' object has no attribute 'create_session' at Mon Nov 29 01:41:23 2021
Error with initializing tables: 'DbInitializer' object has no attribute 'create_session' at Mon Nov 29 01:41:47 2021
Error with initializing tables: 'DbInitializer' object has no attribute 'create_session' at Mon Nov 29 01:42:03 2021
Error with creating triggers: (pymysql.err.OperationalError) (1359, 'Trigger already exists')
[SQL: CREATE TRIGGER autoupdatePrice_2 AFTER UPDATE ON Service
                                FOR EACH ROW BEGIN
                                    INSERT INTO PriceHistory(ServiceName, CompanyName, Price) VALUES (NEW.ServiceName, NEW.CompanyName, NEW.ServicePrice);
                                END]
(Background on this error at: https://sqlalche.me/e/14/e3q8) at Sun Dec  5 10:24:05 2021
Error with clearing tables: (pymysql.err.ProgrammingError) (1146, "Table 'BrokerBase.Account' doesn't exist")
[SQL: DELETE FROM `Account`]
(Background on this error at: https://sqlalche.me/e/14/f405) at Sun Dec  5 21:15:11 2021
Error with initializing tables: (pymysql.err.OperationalError) (3819, "Check constraint 'ch_password' is violated.")
[SQL: INSERT INTO `Account` (`ID`, `AccountLogin`, `AccountPassword`, `MobileNumber`, `Email`, `Rolename`) VALUES (%(ID)s, %(AccountLogin)s, %(AccountPassword)s, %(MobileNumber)s, %(Email)s, %(Rolename)s)]
[parameters: {'ID': 1000, 'AccountLogin': 'ur_god', 'AccountPassword': 'god_pass', 'MobileNumber': '+375(99)999-99-99', 'Email': 'godemail@god.ru', 'Rolename': 'BROKER'}]
(Background on this error at: https://sqlalche.me/e/14/e3q8) at Sun Dec  5 21:32:17 2021
Error with initializing tables: (pymysql.err.OperationalError) (3819, "Check constraint 'ch_password' is violated.")
[SQL: INSERT INTO `Account` (`ID`, `AccountLogin`, `AccountPassword`, `MobileNumber`, `Email`, `Rolename`) VALUES (%(ID)s, %(AccountLogin)s, %(AccountPassword)s, %(MobileNumber)s, %(Email)s, %(Rolename)s)]
[parameters: {'ID': 1000, 'AccountLogin': 'ur_god', 'AccountPassword': 'god_pass', 'MobileNumber': '+375(99)999-99-99', 'Email': 'godemail@god.ru', 'Rolename': 'BROKER'}]
(Background on this error at: https://sqlalche.me/e/14/e3q8) at Sun Dec  5 21:32:38 2021
Error with initializing tables: name 'os' is not defined at Sun Dec  5 21:35:39 2021
Error with initializing tables: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'Газпром' for key 'Company.CompanyName'")
[SQL: INSERT INTO `Company` (`CompanyName`) VALUES (%(CompanyName)s)]
[parameters: {'CompanyName': 'Газпром'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) at Mon Dec  6 07:18:44 2021
Error with clearing tables: (pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`BrokerBase`.`BanList`, CONSTRAINT `fkey_account` FOREIGN KEY (`Account_ID`) REFERENCES `Account` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE)')
[SQL: DELETE FROM `Account`]
(Background on this error at: https://sqlalche.me/e/14/gkpj) at Tue Dec  7 05:42:08 2021
Error with clearing tables: (pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`BrokerBase`.`BanList`, CONSTRAINT `fkey_account` FOREIGN KEY (`Account_ID`) REFERENCES `Account` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE)')
[SQL: DELETE FROM `Account`]
(Background on this error at: https://sqlalche.me/e/14/gkpj) at Tue Dec  7 05:42:40 2021
Error with clearing tables: (pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`BrokerBase`.`BanList`, CONSTRAINT `fkey_account` FOREIGN KEY (`Account_ID`) REFERENCES `Account` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE)')
[SQL: DELETE FROM `Account`]
(Background on this error at: https://sqlalche.me/e/14/gkpj) at Tue Dec  7 05:43:25 2021
